workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Margen Attack-Data API:
        inputs:
            - location: ./openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/margen/margen-api/margen-attack-data-api
targets:
    margen:
        target: python
        source: Margen Attack-Data API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/margen/margen-api/margen-attack-data-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
