"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
import httpx
from jsonpath import JSONPath
from margen import errors, models, utils
from margen._hooks import HookContext, SDKHooks
from margen.types import OptionalNullable, UNSET
from margen.utils import get_security_from_env
from margen.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Awaitable, Callable, Dict, List, Mapping, Optional, Union, cast
import weakref


class Margen(BaseSDK):
    r"""Margen Attack-Data API: Credit-metered API that delivers labeled deepfake attack-data (real vs AI-generated face images and their platform-perturbed variants). Data is organized into benchmarks (versioned datasets, e.g. synthetic-face-v1), each with its own queryable dimensions. Auth: Bearer token. Pull one image per credit; test keys pull a free fixed sample. The canonical path prefix is /api/v1/data; the unversioned /api/data prefix remains a permanent alias."""

    def __init__(
        self,
        bearer_auth: Optional[Union[Optional[str], Callable[[], Optional[str]]]] = None,
        server_idx: Optional[int] = None,
        url_params: Optional[Dict[str, str]] = None,
        server_url: Optional[str] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param bearer_auth: The bearer_auth required for authentication
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client(follow_redirects=True)
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient(follow_redirects=True)
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        security: Any = None
        if bearer_auth is None:
            security = None
        elif callable(bearer_auth):
            # pylint: disable=unnecessary-lambda-assignment
            security = lambda: models.Security(bearer_auth=bearer_auth())
        else:
            security = models.Security(bearer_auth=bearer_auth)

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None

    def list_benchmarks(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.BenchmarkList:
        r"""List benchmarks the key can query

        Returns the benchmarks visible to the key. Pick an id and pass it as the `benchmark` parameter on /catalog and /items.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request(
            method="GET",
            path="/api/v1/data/benchmarks",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listBenchmarks",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=None,
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.BenchmarkList, http_res)
        if utils.match_response(http_res, ["401", "429"], "application/json"):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.MargenDefaultError("Unexpected response received", http_res)

    async def list_benchmarks_async(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.BenchmarkList:
        r"""List benchmarks the key can query

        Returns the benchmarks visible to the key. Pick an id and pass it as the `benchmark` parameter on /catalog and /items.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request_async(
            method="GET",
            path="/api/v1/data/benchmarks",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listBenchmarks",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=None,
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.BenchmarkList, http_res)
        if utils.match_response(http_res, ["401", "429"], "application/json"):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.MargenDefaultError("Unexpected response received", http_res)

    def get_catalog(
        self,
        *,
        benchmark: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.Catalog:
        r"""Dimensions and allowed values for a benchmark

        Self-describing catalog for one benchmark: each dimension with its allowed values, plus a `filters` map of query-param to allowed values. This is the runtime source of truth for what a benchmark supports (the API is registry-driven; do not hardcode dimension values in a client).

        :param benchmark: Benchmark id (e.g. synthetic-face-v1). Effectively required: omitting it works only while the key sees exactly one benchmark; once a second exists, omission returns 400 listing the available ids.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetCatalogRequest(
            benchmark=benchmark,
        )

        req = self._build_request(
            method="GET",
            path="/api/v1/data/catalog",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getCatalog",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=None,
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Catalog, http_res)
        if utils.match_response(
            http_res, ["400", "401", "404", "429"], "application/json"
        ):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.MargenDefaultError("Unexpected response received", http_res)

    async def get_catalog_async(
        self,
        *,
        benchmark: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.Catalog:
        r"""Dimensions and allowed values for a benchmark

        Self-describing catalog for one benchmark: each dimension with its allowed values, plus a `filters` map of query-param to allowed values. This is the runtime source of truth for what a benchmark supports (the API is registry-driven; do not hardcode dimension values in a client).

        :param benchmark: Benchmark id (e.g. synthetic-face-v1). Effectively required: omitting it works only while the key sees exactly one benchmark; once a second exists, omission returns 400 listing the available ids.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetCatalogRequest(
            benchmark=benchmark,
        )

        req = self._build_request_async(
            method="GET",
            path="/api/v1/data/catalog",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getCatalog",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=None,
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Catalog, http_res)
        if utils.match_response(
            http_res, ["400", "401", "404", "429"], "application/json"
        ):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.MargenDefaultError("Unexpected response received", http_res)

    def list_items(
        self,
        *,
        benchmark: Optional[str] = None,
        skin_tone: Optional[str] = None,
        gender: Optional[str] = None,
        kind: Optional[models.ListItemsKind] = None,
        generator: Optional[str] = None,
        perturbation: Optional[str] = None,
        condition: Optional[str] = None,
        layer: Optional[str] = None,
        base_id: Optional[str] = None,
        source_real_id: Optional[str] = None,
        scene: Optional[str] = None,
        include: Optional[str] = None,
        limit: Optional[int] = 100,
        offset: Optional[int] = 0,
        cursor: Optional[str] = None,
        lineage: Optional[models.Lineage] = None,
        exclude_owned: Optional[models.ExcludeOwned] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Optional[models.ListItemsResponse]:
        r"""Select items for a benchmark

        Filterable list of items (ids + attributes, no storage paths). Any filter accepts a comma-separated list, which matches any of the values (OR within a dimension); separate params must all hold (AND across dimensions). Omit a dimension to include all of its values. Fixed dimensions validate and return 400 on an unknown value.

        Dimension filters are benchmark-defined: the ones below cover synthetic-face-v1; call /catalog for a benchmark's actual dimensions and values. Additional per-benchmark dimensions are queried by their catalog `key`.

        Pagination has three modes: (1) offset (default: `limit`/`offset`, exact `total`, `has_more`; no cursor), (2) cursor (`cursor` set: keyset, `total` null, `next_cursor` set), (3) lineage (`lineage=true`: pages whole lineages; `limit`/`offset` count lineages, `total_lineages`/`lineages` returned, no cursor).

        The x-speakeasy-pagination extension on this operation describes cursor mode only: a generated SDK auto-pages by feeding `next_cursor` back into the `cursor` query param. Offset and lineage modes are paged manually.

        :param benchmark: Benchmark id (e.g. synthetic-face-v1). Effectively required: omitting it works only while the key sees exactly one benchmark; once a second exists, omission returns 400 listing the available ids.
        :param skin_tone: Demographic cell skin-tone band(s), comma-separated. Values per /catalog (e.g. very_light,light,intermediate,tan,brown,dark).
        :param gender: Demographic cell gender(s), comma-separated (e.g. female,male).
        :param kind: real (genuine, unmodified) or fake (AI-generated). Comma-separated allowed.
        :param generator: Generator model(s) (fake only). Values per /catalog.
        :param perturbation: Condition(s) applied. Values per /catalog (e.g. clean,jpeg_q70,fb_pipeline). Alias: `condition`.
        :param condition: Alias for `perturbation`.
        :param layer: Perturbation layer(s) (clean, layer1, layer2, layer2_recropped).
        :param base_id: Pull every perturbation of one base image. Take an item's base_id and add &perturbation=... to fetch a specific condition of the same image.
        :param source_real_id: Pull the full lineage descended from one sourced real image.
        :param scene: Synthetic-only semantic context: indoor | outdoor | selfie. Comma-separated allowed. Real images have no scene (null), so filtering by scene restricts to synthetics; scene together with kind=real is empty by construction.
        :param include: Opt-in extras, comma-separated. Pass `metadata` to attach the full per-image label object (skin tone, gender, age, scene, occlusion, difficulty, image spec, and confidences) to each item under `metadata`. Browsing labels is free (no bytes, no credit); only /download costs a credit. Fields are listed by /catalog.
        :param limit: Page size. Values above 500 are clamped; the response sets limit_clamped.
        :param offset: Pagination offset (offset/lineage modes).
        :param cursor: Keyset cursor from a prior response's next_cursor (cursor mode).
        :param lineage: Set to true to page over whole lineages.
        :param exclude_owned: Offset mode only. Omit items you already own (credits are used per unique image, so owned items are free re-downloads). The response adds remaining/owned/total_matching and subset_exhausted with a message when you own the whole matching subset.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListItemsRequest(
            benchmark=benchmark,
            skin_tone=skin_tone,
            gender=gender,
            kind=kind,
            generator=generator,
            perturbation=perturbation,
            condition=condition,
            layer=layer,
            base_id=base_id,
            source_real_id=source_real_id,
            scene=scene,
            include=include,
            limit=limit,
            offset=offset,
            cursor=cursor,
            lineage=lineage,
            exclude_owned=exclude_owned,
        )

        req = self._build_request(
            method="GET",
            path="/api/v1/data/items",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listItems",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=None,
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        def next_func() -> Optional[models.ListItemsResponse]:
            body = utils.unmarshal_json(http_res.text, Union[Dict[Any, Any], List[Any]])

            next_cursor = JSONPath("$.next_cursor").parse(body)

            if len(next_cursor) == 0:
                return None

            next_cursor = next_cursor[0]
            if next_cursor is None or str(next_cursor).strip() == "":
                return None

            return self.list_items(
                benchmark=benchmark,
                skin_tone=skin_tone,
                gender=gender,
                kind=kind,
                generator=generator,
                perturbation=perturbation,
                condition=condition,
                layer=layer,
                base_id=base_id,
                source_real_id=source_real_id,
                scene=scene,
                include=include,
                limit=limit,
                offset=offset,
                cursor=next_cursor,
                lineage=lineage,
                exclude_owned=exclude_owned,
                retries=retries,
                server_url=server_url,
                timeout_ms=timeout_ms,
                http_headers=http_headers,
            )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.ListItemsResponse(
                result=unmarshal_json_response(models.ItemList, http_res),
                next=next_func,
            )
        if utils.match_response(
            http_res, ["400", "401", "404", "429"], "application/json"
        ):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.MargenDefaultError("Unexpected response received", http_res)

    async def list_items_async(
        self,
        *,
        benchmark: Optional[str] = None,
        skin_tone: Optional[str] = None,
        gender: Optional[str] = None,
        kind: Optional[models.ListItemsKind] = None,
        generator: Optional[str] = None,
        perturbation: Optional[str] = None,
        condition: Optional[str] = None,
        layer: Optional[str] = None,
        base_id: Optional[str] = None,
        source_real_id: Optional[str] = None,
        scene: Optional[str] = None,
        include: Optional[str] = None,
        limit: Optional[int] = 100,
        offset: Optional[int] = 0,
        cursor: Optional[str] = None,
        lineage: Optional[models.Lineage] = None,
        exclude_owned: Optional[models.ExcludeOwned] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Optional[models.ListItemsResponse]:
        r"""Select items for a benchmark

        Filterable list of items (ids + attributes, no storage paths). Any filter accepts a comma-separated list, which matches any of the values (OR within a dimension); separate params must all hold (AND across dimensions). Omit a dimension to include all of its values. Fixed dimensions validate and return 400 on an unknown value.

        Dimension filters are benchmark-defined: the ones below cover synthetic-face-v1; call /catalog for a benchmark's actual dimensions and values. Additional per-benchmark dimensions are queried by their catalog `key`.

        Pagination has three modes: (1) offset (default: `limit`/`offset`, exact `total`, `has_more`; no cursor), (2) cursor (`cursor` set: keyset, `total` null, `next_cursor` set), (3) lineage (`lineage=true`: pages whole lineages; `limit`/`offset` count lineages, `total_lineages`/`lineages` returned, no cursor).

        The x-speakeasy-pagination extension on this operation describes cursor mode only: a generated SDK auto-pages by feeding `next_cursor` back into the `cursor` query param. Offset and lineage modes are paged manually.

        :param benchmark: Benchmark id (e.g. synthetic-face-v1). Effectively required: omitting it works only while the key sees exactly one benchmark; once a second exists, omission returns 400 listing the available ids.
        :param skin_tone: Demographic cell skin-tone band(s), comma-separated. Values per /catalog (e.g. very_light,light,intermediate,tan,brown,dark).
        :param gender: Demographic cell gender(s), comma-separated (e.g. female,male).
        :param kind: real (genuine, unmodified) or fake (AI-generated). Comma-separated allowed.
        :param generator: Generator model(s) (fake only). Values per /catalog.
        :param perturbation: Condition(s) applied. Values per /catalog (e.g. clean,jpeg_q70,fb_pipeline). Alias: `condition`.
        :param condition: Alias for `perturbation`.
        :param layer: Perturbation layer(s) (clean, layer1, layer2, layer2_recropped).
        :param base_id: Pull every perturbation of one base image. Take an item's base_id and add &perturbation=... to fetch a specific condition of the same image.
        :param source_real_id: Pull the full lineage descended from one sourced real image.
        :param scene: Synthetic-only semantic context: indoor | outdoor | selfie. Comma-separated allowed. Real images have no scene (null), so filtering by scene restricts to synthetics; scene together with kind=real is empty by construction.
        :param include: Opt-in extras, comma-separated. Pass `metadata` to attach the full per-image label object (skin tone, gender, age, scene, occlusion, difficulty, image spec, and confidences) to each item under `metadata`. Browsing labels is free (no bytes, no credit); only /download costs a credit. Fields are listed by /catalog.
        :param limit: Page size. Values above 500 are clamped; the response sets limit_clamped.
        :param offset: Pagination offset (offset/lineage modes).
        :param cursor: Keyset cursor from a prior response's next_cursor (cursor mode).
        :param lineage: Set to true to page over whole lineages.
        :param exclude_owned: Offset mode only. Omit items you already own (credits are used per unique image, so owned items are free re-downloads). The response adds remaining/owned/total_matching and subset_exhausted with a message when you own the whole matching subset.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ListItemsRequest(
            benchmark=benchmark,
            skin_tone=skin_tone,
            gender=gender,
            kind=kind,
            generator=generator,
            perturbation=perturbation,
            condition=condition,
            layer=layer,
            base_id=base_id,
            source_real_id=source_real_id,
            scene=scene,
            include=include,
            limit=limit,
            offset=offset,
            cursor=cursor,
            lineage=lineage,
            exclude_owned=exclude_owned,
        )

        req = self._build_request_async(
            method="GET",
            path="/api/v1/data/items",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="listItems",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=None,
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        def next_func() -> Awaitable[Optional[models.ListItemsResponse]]:
            body = utils.unmarshal_json(http_res.text, Union[Dict[Any, Any], List[Any]])

            async def empty_result():
                return None

            next_cursor = JSONPath("$.next_cursor").parse(body)

            if len(next_cursor) == 0:
                return empty_result()

            next_cursor = next_cursor[0]
            if next_cursor is None or str(next_cursor).strip() == "":
                return empty_result()

            return self.list_items_async(
                benchmark=benchmark,
                skin_tone=skin_tone,
                gender=gender,
                kind=kind,
                generator=generator,
                perturbation=perturbation,
                condition=condition,
                layer=layer,
                base_id=base_id,
                source_real_id=source_real_id,
                scene=scene,
                include=include,
                limit=limit,
                offset=offset,
                cursor=next_cursor,
                lineage=lineage,
                exclude_owned=exclude_owned,
                retries=retries,
                server_url=server_url,
                timeout_ms=timeout_ms,
                http_headers=http_headers,
            )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.ListItemsResponse(
                result=unmarshal_json_response(models.ItemList, http_res),
                next=next_func,
            )
        if utils.match_response(
            http_res, ["400", "401", "404", "429"], "application/json"
        ):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.MargenDefaultError("Unexpected response received", http_res)

    def download_item(
        self,
        *,
        item_id: str,
        idempotency_key: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.Download:
        r"""Get a signed URL for one item

        Returns JSON with a short-lived signed URL (not the image bytes). Fetch `url` with a plain HTTP client and NO auth header, within `expires_in` seconds. On the live tier this debits one credit before returning the URL; test items are free. Send an Idempotency-Key header so a retry of the same item is a no-op (not a second charge). On a zero balance returns 402 with code insufficient_credits.

        :param item_id: The item id from /items.
        :param idempotency_key: Stable per item across retries so a retried download is not charged twice.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DownloadItemRequest(
            item_id=item_id,
            idempotency_key=idempotency_key,
        )

        req = self._build_request(
            method="GET",
            path="/api/v1/data/download/{itemId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="downloadItem",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=None,
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Download, http_res)
        if utils.match_response(
            http_res, ["401", "402", "403", "404", "429"], "application/json"
        ):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.MargenDefaultError("Unexpected response received", http_res)

    async def download_item_async(
        self,
        *,
        item_id: str,
        idempotency_key: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.Download:
        r"""Get a signed URL for one item

        Returns JSON with a short-lived signed URL (not the image bytes). Fetch `url` with a plain HTTP client and NO auth header, within `expires_in` seconds. On the live tier this debits one credit before returning the URL; test items are free. Send an Idempotency-Key header so a retry of the same item is a no-op (not a second charge). On a zero balance returns 402 with code insufficient_credits.

        :param item_id: The item id from /items.
        :param idempotency_key: Stable per item across retries so a retried download is not charged twice.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DownloadItemRequest(
            item_id=item_id,
            idempotency_key=idempotency_key,
        )

        req = self._build_request_async(
            method="GET",
            path="/api/v1/data/download/{itemId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="downloadItem",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=None,
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Download, http_res)
        if utils.match_response(
            http_res, ["401", "402", "403", "404", "429"], "application/json"
        ):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.MargenDefaultError("Unexpected response received", http_res)

    def get_usage(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.Usage:
        r"""Current tier and credit balance

        The key owner's tier and credit balance. Check before a large pull to avoid a mid-run 402.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request(
            method="GET",
            path="/api/v1/data/usage",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getUsage",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=None,
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Usage, http_res)
        if utils.match_response(http_res, ["401", "429"], "application/json"):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.MargenDefaultError("Unexpected response received", http_res)

    async def get_usage_async(
        self,
        *,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.Usage:
        r"""Current tier and credit balance

        The key owner's tier and credit balance. Check before a large pull to avoid a mid-run 402.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)
        req = self._build_request_async(
            method="GET",
            path="/api/v1/data/usage",
            base_url=base_url,
            url_variables=url_variables,
            request=None,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getUsage",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
                tags=None,
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.Usage, http_res)
        if utils.match_response(http_res, ["401", "429"], "application/json"):
            response_data = unmarshal_json_response(errors.ErrorData, http_res)
            raise errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.MargenDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.MargenDefaultError("Unexpected response received", http_res)
