"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from margen.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .attackdataitem import AttackDataItem, AttackDataItemTypedDict, Kind
    from .benchmark import Benchmark, BenchmarkTypedDict
    from .benchmarklist import BenchmarkList, BenchmarkListTier, BenchmarkListTypedDict
    from .catalog import Catalog, CatalogTier, CatalogTypedDict
    from .catalogdimension import CatalogDimension, CatalogDimensionTypedDict, Source
    from .dimensionvalue import DimensionValue, DimensionValueTypedDict
    from .download import Download, DownloadTypedDict
    from .downloaditemop import DownloadItemRequest, DownloadItemRequestTypedDict
    from .error import Available, AvailableTypedDict, Code
    from .getcatalogop import GetCatalogRequest, GetCatalogRequestTypedDict
    from .itemlist import ItemList, ItemListTypedDict, Mode
    from .listitemsop import (
        Lineage,
        ListItemsKind,
        ListItemsRequest,
        ListItemsRequestTypedDict,
        ListItemsResponse,
        ListItemsResponseTypedDict,
    )
    from .security import Security, SecurityTypedDict
    from .usage import Usage, UsageTier, UsageTypedDict

__all__ = [
    "AttackDataItem",
    "AttackDataItemTypedDict",
    "Available",
    "AvailableTypedDict",
    "Benchmark",
    "BenchmarkList",
    "BenchmarkListTier",
    "BenchmarkListTypedDict",
    "BenchmarkTypedDict",
    "Catalog",
    "CatalogDimension",
    "CatalogDimensionTypedDict",
    "CatalogTier",
    "CatalogTypedDict",
    "Code",
    "DimensionValue",
    "DimensionValueTypedDict",
    "Download",
    "DownloadItemRequest",
    "DownloadItemRequestTypedDict",
    "DownloadTypedDict",
    "GetCatalogRequest",
    "GetCatalogRequestTypedDict",
    "ItemList",
    "ItemListTypedDict",
    "Kind",
    "Lineage",
    "ListItemsKind",
    "ListItemsRequest",
    "ListItemsRequestTypedDict",
    "ListItemsResponse",
    "ListItemsResponseTypedDict",
    "Mode",
    "Security",
    "SecurityTypedDict",
    "Source",
    "Usage",
    "UsageTier",
    "UsageTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AttackDataItem": ".attackdataitem",
    "AttackDataItemTypedDict": ".attackdataitem",
    "Kind": ".attackdataitem",
    "Benchmark": ".benchmark",
    "BenchmarkTypedDict": ".benchmark",
    "BenchmarkList": ".benchmarklist",
    "BenchmarkListTier": ".benchmarklist",
    "BenchmarkListTypedDict": ".benchmarklist",
    "Catalog": ".catalog",
    "CatalogTier": ".catalog",
    "CatalogTypedDict": ".catalog",
    "CatalogDimension": ".catalogdimension",
    "CatalogDimensionTypedDict": ".catalogdimension",
    "Source": ".catalogdimension",
    "DimensionValue": ".dimensionvalue",
    "DimensionValueTypedDict": ".dimensionvalue",
    "Download": ".download",
    "DownloadTypedDict": ".download",
    "DownloadItemRequest": ".downloaditemop",
    "DownloadItemRequestTypedDict": ".downloaditemop",
    "Available": ".error",
    "AvailableTypedDict": ".error",
    "Code": ".error",
    "GetCatalogRequest": ".getcatalogop",
    "GetCatalogRequestTypedDict": ".getcatalogop",
    "ItemList": ".itemlist",
    "ItemListTypedDict": ".itemlist",
    "Mode": ".itemlist",
    "Lineage": ".listitemsop",
    "ListItemsKind": ".listitemsop",
    "ListItemsRequest": ".listitemsop",
    "ListItemsRequestTypedDict": ".listitemsop",
    "ListItemsResponse": ".listitemsop",
    "ListItemsResponseTypedDict": ".listitemsop",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "Usage": ".usage",
    "UsageTier": ".usage",
    "UsageTypedDict": ".usage",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
