"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from margen.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from margen.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


Kind = Union[
    Literal[
        "real",
        "fake",
    ],
    UnrecognizedStr,
]


class AttackDataItemTypedDict(TypedDict):
    id: str
    r"""This exact image (a variant). Pass to /api/v1/data/download/{itemId}."""
    benchmark: str
    kind: Kind
    object: Literal["attack_data_item"]
    skin_tone: NotRequired[Nullable[str]]
    gender: NotRequired[Nullable[str]]
    generator: NotRequired[Nullable[str]]
    r"""Generator model (fake only)."""
    perturbation: NotRequired[Nullable[str]]
    layer: NotRequired[Nullable[str]]
    base_id: NotRequired[Nullable[str]]
    r"""The base image this variant derives from. Hold base_id and change perturbation to pull another condition of the SAME image; all perturbations of one image share it."""
    source_real_id: NotRequired[Nullable[str]]
    r"""Lineage key; the real source this descends from. All variants of one source (the real, its fakes, and their perturbations) share it."""
    scene: NotRequired[Nullable[str]]
    r"""Synthetic-only semantic context: indoor | outdoor | selfie. null for real images."""
    variant_group: NotRequired[Nullable[str]]
    r"""Opaque id grouping near-duplicate synthetic siblings from one generation cluster; null for reals. Navigation/lineage only (pull siblings or dedup), never a billing bundle; exposes no seed or prompt."""
    attributes: NotRequired[Dict[str, Any]]
    r"""Benchmark-specific fields; {} when the benchmark has none."""
    metadata: NotRequired[Nullable[Dict[str, Any]]]
    r"""The full per-image label object (skin tone incl. ITA, gender + cross-checks, age/race, scene/face/occlusion + confidences, difficulty, image spec). Present ONLY when the request passes include=metadata (on /items or /download); omitted otherwise. Flat and stable, so a streamed result builds a consistent table. Field schema is published by /catalog. Browsing labels is free; only /download costs a credit."""


class AttackDataItem(BaseModel):
    id: str
    r"""This exact image (a variant). Pass to /api/v1/data/download/{itemId}."""

    benchmark: str

    kind: Kind

    object: Annotated[
        Annotated[
            Literal["attack_data_item"],
            AfterValidator(validate_const("attack_data_item")),
        ],
        pydantic.Field(alias="object"),
    ] = "attack_data_item"

    skin_tone: OptionalNullable[str] = UNSET

    gender: OptionalNullable[str] = UNSET

    generator: OptionalNullable[str] = UNSET
    r"""Generator model (fake only)."""

    perturbation: OptionalNullable[str] = UNSET

    layer: OptionalNullable[str] = UNSET

    base_id: OptionalNullable[str] = UNSET
    r"""The base image this variant derives from. Hold base_id and change perturbation to pull another condition of the SAME image; all perturbations of one image share it."""

    source_real_id: OptionalNullable[str] = UNSET
    r"""Lineage key; the real source this descends from. All variants of one source (the real, its fakes, and their perturbations) share it."""

    scene: OptionalNullable[str] = UNSET
    r"""Synthetic-only semantic context: indoor | outdoor | selfie. null for real images."""

    variant_group: OptionalNullable[str] = UNSET
    r"""Opaque id grouping near-duplicate synthetic siblings from one generation cluster; null for reals. Navigation/lineage only (pull siblings or dedup), never a billing bundle; exposes no seed or prompt."""

    attributes: Optional[Dict[str, Any]] = None
    r"""Benchmark-specific fields; {} when the benchmark has none."""

    metadata: OptionalNullable[Dict[str, Any]] = UNSET
    r"""The full per-image label object (skin tone incl. ITA, gender + cross-checks, age/race, scene/face/occlusion + confidences, difficulty, image spec). Present ONLY when the request passes include=metadata (on /items or /download); omitted otherwise. Flat and stable, so a streamed result builds a consistent table. Field schema is published by /catalog. Browsing labels is free; only /download costs a credit."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "skin_tone",
                "gender",
                "generator",
                "perturbation",
                "layer",
                "base_id",
                "source_real_id",
                "scene",
                "variant_group",
                "attributes",
                "metadata",
            ]
        )
        nullable_fields = set(
            [
                "skin_tone",
                "gender",
                "generator",
                "perturbation",
                "layer",
                "base_id",
                "source_real_id",
                "scene",
                "variant_group",
                "metadata",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AttackDataItem.model_rebuild()
except NameError:
    pass
