"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from margen.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from margen.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


Kind = Union[
    Literal[
        "real",
        "fake",
    ],
    UnrecognizedStr,
]


class AttackDataItemTypedDict(TypedDict):
    id: str
    r"""Pass to /api/v1/data/download/{itemId}."""
    benchmark: str
    kind: Kind
    object: Literal["attack_data_item"]
    skin_tone: NotRequired[Nullable[str]]
    gender: NotRequired[Nullable[str]]
    generator: NotRequired[Nullable[str]]
    r"""Generator model (fake only)."""
    perturbation: NotRequired[Nullable[str]]
    layer: NotRequired[Nullable[str]]
    source_real_id: NotRequired[Nullable[str]]
    r"""Lineage key; all variants of one source share it."""
    source_dataset: NotRequired[Nullable[str]]
    r"""Provenance / license source (e.g. pexels)."""
    attributes: NotRequired[Dict[str, Any]]
    r"""Benchmark-specific fields; {} when the benchmark has none."""


class AttackDataItem(BaseModel):
    id: str
    r"""Pass to /api/v1/data/download/{itemId}."""

    benchmark: str

    kind: Kind

    object: Annotated[
        Annotated[
            Literal["attack_data_item"],
            AfterValidator(validate_const("attack_data_item")),
        ],
        pydantic.Field(alias="object"),
    ] = "attack_data_item"

    skin_tone: OptionalNullable[str] = UNSET

    gender: OptionalNullable[str] = UNSET

    generator: OptionalNullable[str] = UNSET
    r"""Generator model (fake only)."""

    perturbation: OptionalNullable[str] = UNSET

    layer: OptionalNullable[str] = UNSET

    source_real_id: OptionalNullable[str] = UNSET
    r"""Lineage key; all variants of one source share it."""

    source_dataset: OptionalNullable[str] = UNSET
    r"""Provenance / license source (e.g. pexels)."""

    attributes: Optional[Dict[str, Any]] = None
    r"""Benchmark-specific fields; {} when the benchmark has none."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "skin_tone",
                "gender",
                "generator",
                "perturbation",
                "layer",
                "source_real_id",
                "source_dataset",
                "attributes",
            ]
        )
        nullable_fields = set(
            [
                "skin_tone",
                "gender",
                "generator",
                "perturbation",
                "layer",
                "source_real_id",
                "source_dataset",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AttackDataItem.model_rebuild()
except NameError:
    pass
