"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dimensionvalue import DimensionValue, DimensionValueTypedDict
from margen.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


Source = Union[
    Literal[
        "column",
        "attribute",
    ],
    UnrecognizedStr,
]


class CatalogDimensionTypedDict(TypedDict):
    key: str
    r"""The query-param name."""
    label: str
    source: Source
    alias: NotRequired[str]
    values: NotRequired[List[DimensionValueTypedDict]]
    r"""Allowed values (labeled). Absent for lineage keys."""
    lineage: NotRequired[bool]
    note: NotRequired[str]


class CatalogDimension(BaseModel):
    key: str
    r"""The query-param name."""

    label: str

    source: Source

    alias: Optional[str] = None

    values: Optional[List[DimensionValue]] = None
    r"""Allowed values (labeled). Absent for lineage keys."""

    lineage: Optional[bool] = None

    note: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["alias", "values", "lineage", "note"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
