"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .benchmark import Benchmark, BenchmarkTypedDict
from .catalogdimension import CatalogDimension, CatalogDimensionTypedDict
from margen.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from margen.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


CatalogTier = Union[
    Literal[
        "test",
        "live",
    ],
    UnrecognizedStr,
]


class CatalogTypedDict(TypedDict):
    benchmark: BenchmarkTypedDict
    tier: CatalogTier
    dimensions: List[CatalogDimensionTypedDict]
    filters: Dict[str, Any]
    r"""Map of query-param to allowed values (self-describing)."""
    object: Literal["catalog"]
    total: NotRequired[int]


class Catalog(BaseModel):
    benchmark: Benchmark

    tier: CatalogTier

    dimensions: List[CatalogDimension]

    filters: Dict[str, Any]
    r"""Map of query-param to allowed values (self-describing)."""

    object: Annotated[
        Annotated[Literal["catalog"], AfterValidator(validate_const("catalog"))],
        pydantic.Field(alias="object"),
    ] = "catalog"

    total: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["total"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Catalog.model_rebuild()
except NameError:
    pass
