"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .attackdataitem import AttackDataItem, AttackDataItemTypedDict
from margen.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from margen.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DownloadTypedDict(TypedDict):
    url: str
    r"""Short-lived signed URL for one image (JPEG). Fetch with no auth header."""
    expires_in: int
    r"""Seconds until the signed URL expires (300)."""
    item: AttackDataItemTypedDict
    object: Literal["download"]
    balance: NotRequired[Nullable[int]]
    r"""Credit balance after the debit; null for free test items."""
    charged: NotRequired[bool]
    r"""true if this pull debited a credit. false for free test items and for re-downloads of an item you already own (credits are used per unique image)."""
    already_owned: NotRequired[bool]
    r"""true if you had already pulled this item; the URL is returned again for free, no debit."""


class Download(BaseModel):
    url: str
    r"""Short-lived signed URL for one image (JPEG). Fetch with no auth header."""

    expires_in: int
    r"""Seconds until the signed URL expires (300)."""

    item: AttackDataItem

    object: Annotated[
        Annotated[Literal["download"], AfterValidator(validate_const("download"))],
        pydantic.Field(alias="object"),
    ] = "download"

    balance: OptionalNullable[int] = UNSET
    r"""Credit balance after the debit; null for free test items."""

    charged: Optional[bool] = None
    r"""true if this pull debited a credit. false for free test items and for re-downloads of an item you already own (credits are used per unique image)."""

    already_owned: Optional[bool] = None
    r"""true if you had already pulled this item; the URL is returned again for free, no debit."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["balance", "charged", "already_owned"])
        nullable_fields = set(["balance"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    Download.model_rebuild()
except NameError:
    pass
