"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from margen.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


Code = Union[
    Literal[
        "unauthorized",
        "insufficient_credits",
        "forbidden_tier",
        "not_found",
        "unknown_benchmark",
        "ambiguous_benchmark",
        "invalid_param",
        "invalid_cursor",
        "rate_limited",
        "service_unconfigured",
        "server_error",
    ],
    UnrecognizedStr,
]
r"""Stable machine-readable error code. Branch on this, not on the message text."""


class AvailableTypedDict(TypedDict):
    id: NotRequired[str]
    title: NotRequired[str]
    product: NotRequired[str]


class Available(BaseModel):
    id: Optional[str] = None

    title: Optional[str] = None

    product: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "title", "product"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
