"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .attackdataitem import AttackDataItem, AttackDataItemTypedDict
from margen.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from margen.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Dict, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


Mode = Union[
    Literal[
        "offset",
        "cursor",
        "lineage",
    ],
    UnrecognizedStr,
]


class ItemListTypedDict(TypedDict):
    r"""Standard list envelope plus /items echo fields. total is null in cursor and lineage modes."""

    data: List[AttackDataItemTypedDict]
    has_more: bool
    object: Literal["list"]
    total: NotRequired[Nullable[int]]
    r"""Exact count in offset mode; null in cursor/lineage modes."""
    next_cursor: NotRequired[Nullable[str]]
    r"""Set in cursor mode only."""
    benchmark: NotRequired[str]
    mode: NotRequired[Mode]
    applied_filters: NotRequired[Dict[str, Nullable[List[str]]]]
    r"""Echo of the filters the query understood; null means the dimension was not filtered."""
    limit: NotRequired[int]
    offset: NotRequired[int]
    limit_clamped: NotRequired[bool]
    r"""True when the requested limit exceeded the max and was clamped."""
    total_lineages: NotRequired[int]
    r"""Lineage mode only."""
    lineages: NotRequired[int]
    r"""Lineage mode only: lineages on this page."""


class ItemList(BaseModel):
    r"""Standard list envelope plus /items echo fields. total is null in cursor and lineage modes."""

    data: List[AttackDataItem]

    has_more: bool

    object: Annotated[
        Annotated[Literal["list"], AfterValidator(validate_const("list"))],
        pydantic.Field(alias="object"),
    ] = "list"

    total: OptionalNullable[int] = UNSET
    r"""Exact count in offset mode; null in cursor/lineage modes."""

    next_cursor: OptionalNullable[str] = UNSET
    r"""Set in cursor mode only."""

    benchmark: Optional[str] = None

    mode: Optional[Mode] = None

    applied_filters: Optional[Dict[str, Nullable[List[str]]]] = None
    r"""Echo of the filters the query understood; null means the dimension was not filtered."""

    limit: Optional[int] = None

    offset: Optional[int] = None

    limit_clamped: Optional[bool] = None
    r"""True when the requested limit exceeded the max and was clamped."""

    total_lineages: Optional[int] = None
    r"""Lineage mode only."""

    lineages: Optional[int] = None
    r"""Lineage mode only: lineages on this page."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "total",
                "next_cursor",
                "benchmark",
                "mode",
                "applied_filters",
                "limit",
                "offset",
                "limit_clamped",
                "total_lineages",
                "lineages",
            ]
        )
        nullable_fields = set(["total", "next_cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ItemList.model_rebuild()
except NameError:
    pass
