"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .itemlist import ItemList, ItemListTypedDict
from margen.types import BaseModel, UNSET_SENTINEL
from margen.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Awaitable, Callable, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


ListItemsKind = Literal[
    "real",
    "fake",
]
r"""real (genuine, unmodified) or fake (AI-generated). Comma-separated allowed."""


Lineage = Literal["true",]
r"""Set to true to page over whole lineages."""


class ListItemsRequestTypedDict(TypedDict):
    benchmark: NotRequired[str]
    r"""Benchmark id (e.g. synthetic-face-v1). Effectively required: omitting it works only while the key sees exactly one benchmark; once a second exists, omission returns 400 listing the available ids."""
    skin_tone: NotRequired[str]
    r"""Demographic cell skin-tone band(s), comma-separated. Values per /catalog (e.g. very_light,light,intermediate,tan,brown,dark)."""
    gender: NotRequired[str]
    r"""Demographic cell gender(s), comma-separated (e.g. female,male)."""
    kind: NotRequired[ListItemsKind]
    r"""real (genuine, unmodified) or fake (AI-generated). Comma-separated allowed."""
    generator: NotRequired[str]
    r"""Generator model(s) (fake only). Values per /catalog."""
    perturbation: NotRequired[str]
    r"""Condition(s) applied. Values per /catalog (e.g. clean,jpeg_q70,fb_pipeline). Alias: `condition`."""
    condition: NotRequired[str]
    r"""Alias for `perturbation`."""
    layer: NotRequired[str]
    r"""Perturbation layer(s) (clean, layer1, layer2, layer2_recropped)."""
    source_real_id: NotRequired[str]
    r"""Pull the full lineage descended from one sourced real image."""
    limit: NotRequired[int]
    r"""Page size. Values above 500 are clamped; the response sets limit_clamped."""
    offset: NotRequired[int]
    r"""Pagination offset (offset/lineage modes)."""
    cursor: NotRequired[str]
    r"""Keyset cursor from a prior response's next_cursor (cursor mode)."""
    lineage: NotRequired[Lineage]
    r"""Set to true to page over whole lineages."""


class ListItemsRequest(BaseModel):
    benchmark: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Benchmark id (e.g. synthetic-face-v1). Effectively required: omitting it works only while the key sees exactly one benchmark; once a second exists, omission returns 400 listing the available ids."""

    skin_tone: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Demographic cell skin-tone band(s), comma-separated. Values per /catalog (e.g. very_light,light,intermediate,tan,brown,dark)."""

    gender: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Demographic cell gender(s), comma-separated (e.g. female,male)."""

    kind: Annotated[
        Optional[ListItemsKind],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""real (genuine, unmodified) or fake (AI-generated). Comma-separated allowed."""

    generator: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Generator model(s) (fake only). Values per /catalog."""

    perturbation: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Condition(s) applied. Values per /catalog (e.g. clean,jpeg_q70,fb_pipeline). Alias: `condition`."""

    condition: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Alias for `perturbation`."""

    layer: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Perturbation layer(s) (clean, layer1, layer2, layer2_recropped)."""

    source_real_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pull the full lineage descended from one sourced real image."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100
    r"""Page size. Values above 500 are clamped; the response sets limit_clamped."""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Pagination offset (offset/lineage modes)."""

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Keyset cursor from a prior response's next_cursor (cursor mode)."""

    lineage: Annotated[
        Optional[Lineage],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Set to true to page over whole lineages."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "benchmark",
                "skin_tone",
                "gender",
                "kind",
                "generator",
                "perturbation",
                "condition",
                "layer",
                "source_real_id",
                "limit",
                "offset",
                "cursor",
                "lineage",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListItemsResponseTypedDict(TypedDict):
    result: ItemListTypedDict


class ListItemsResponse(BaseModel):
    next: Union[
        Callable[[], Optional[ListItemsResponse]],
        Callable[[], Awaitable[Optional[ListItemsResponse]]],
    ]

    result: ItemList
