"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .itemlist import ItemList, ItemListTypedDict
from margen.types import BaseModel, UNSET_SENTINEL
from margen.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import Awaitable, Callable, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


ListItemsKind = Literal[
    "real",
    "fake",
]
r"""real (genuine, unmodified) or fake (AI-generated). Comma-separated allowed."""


Lineage = Literal["true",]
r"""Set to true to page over whole lineages."""


ExcludeOwned = Literal["true",]
r"""Offset mode only. Omit items you already own (credits are used per unique image, so owned items are free re-downloads). The response adds remaining/owned/total_matching and subset_exhausted with a message when you own the whole matching subset."""


class ListItemsRequestTypedDict(TypedDict):
    benchmark: NotRequired[str]
    r"""Benchmark id (e.g. synthetic-face-v1). Effectively required: omitting it works only while the key sees exactly one benchmark; once a second exists, omission returns 400 listing the available ids."""
    skin_tone: NotRequired[str]
    r"""Demographic cell skin-tone band(s), comma-separated. Values per /catalog (e.g. very_light,light,intermediate,tan,brown,dark)."""
    gender: NotRequired[str]
    r"""Demographic cell gender(s), comma-separated (e.g. female,male)."""
    kind: NotRequired[ListItemsKind]
    r"""real (genuine, unmodified) or fake (AI-generated). Comma-separated allowed."""
    generator: NotRequired[str]
    r"""Generator model(s) (fake only). Values per /catalog."""
    perturbation: NotRequired[str]
    r"""Condition(s) applied. Values per /catalog (e.g. clean,jpeg_q70,fb_pipeline). Alias: `condition`."""
    condition: NotRequired[str]
    r"""Alias for `perturbation`."""
    layer: NotRequired[str]
    r"""Perturbation layer(s) (clean, layer1, layer2, layer2_recropped)."""
    base_id: NotRequired[str]
    r"""Pull every perturbation of one base image. Take an item's base_id and add &perturbation=... to fetch a specific condition of the same image."""
    source_real_id: NotRequired[str]
    r"""Pull the full lineage descended from one sourced real image."""
    scene: NotRequired[str]
    r"""Synthetic-only semantic context: indoor | outdoor | selfie. Comma-separated allowed. Real images have no scene (null), so filtering by scene restricts to synthetics; scene together with kind=real is empty by construction."""
    variant_group: NotRequired[str]
    r"""Opaque generation-cluster id. Filter by one value to pull every near-duplicate synthetic sibling of that cluster, or dedup to one per group. Reals are null. Grouping/lineage only; it exposes no generation recipe and is not a billing bundle."""
    include: NotRequired[str]
    r"""Opt-in extras, comma-separated. Pass `metadata` to attach the full per-image label object (skin tone, gender, age, scene, occlusion, difficulty, image spec, and confidences) to each item under `metadata`. Browsing labels is free (no bytes, no credit); only /download costs a credit. Fields are listed by /catalog."""
    limit: NotRequired[int]
    r"""Page size. Values above 500 are clamped; the response sets limit_clamped."""
    offset: NotRequired[int]
    r"""Pagination offset (offset/lineage modes)."""
    cursor: NotRequired[str]
    r"""Keyset cursor from a prior response's next_cursor (cursor mode)."""
    lineage: NotRequired[Lineage]
    r"""Set to true to page over whole lineages."""
    exclude_owned: NotRequired[ExcludeOwned]
    r"""Offset mode only. Omit items you already own (credits are used per unique image, so owned items are free re-downloads). The response adds remaining/owned/total_matching and subset_exhausted with a message when you own the whole matching subset."""


class ListItemsRequest(BaseModel):
    benchmark: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Benchmark id (e.g. synthetic-face-v1). Effectively required: omitting it works only while the key sees exactly one benchmark; once a second exists, omission returns 400 listing the available ids."""

    skin_tone: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Demographic cell skin-tone band(s), comma-separated. Values per /catalog (e.g. very_light,light,intermediate,tan,brown,dark)."""

    gender: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Demographic cell gender(s), comma-separated (e.g. female,male)."""

    kind: Annotated[
        Optional[ListItemsKind],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""real (genuine, unmodified) or fake (AI-generated). Comma-separated allowed."""

    generator: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Generator model(s) (fake only). Values per /catalog."""

    perturbation: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Condition(s) applied. Values per /catalog (e.g. clean,jpeg_q70,fb_pipeline). Alias: `condition`."""

    condition: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Alias for `perturbation`."""

    layer: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Perturbation layer(s) (clean, layer1, layer2, layer2_recropped)."""

    base_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pull every perturbation of one base image. Take an item's base_id and add &perturbation=... to fetch a specific condition of the same image."""

    source_real_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pull the full lineage descended from one sourced real image."""

    scene: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Synthetic-only semantic context: indoor | outdoor | selfie. Comma-separated allowed. Real images have no scene (null), so filtering by scene restricts to synthetics; scene together with kind=real is empty by construction."""

    variant_group: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Opaque generation-cluster id. Filter by one value to pull every near-duplicate synthetic sibling of that cluster, or dedup to one per group. Reals are null. Grouping/lineage only; it exposes no generation recipe and is not a billing bundle."""

    include: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Opt-in extras, comma-separated. Pass `metadata` to attach the full per-image label object (skin tone, gender, age, scene, occlusion, difficulty, image spec, and confidences) to each item under `metadata`. Browsing labels is free (no bytes, no credit); only /download costs a credit. Fields are listed by /catalog."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100
    r"""Page size. Values above 500 are clamped; the response sets limit_clamped."""

    offset: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 0
    r"""Pagination offset (offset/lineage modes)."""

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Keyset cursor from a prior response's next_cursor (cursor mode)."""

    lineage: Annotated[
        Optional[Lineage],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Set to true to page over whole lineages."""

    exclude_owned: Annotated[
        Optional[ExcludeOwned],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Offset mode only. Omit items you already own (credits are used per unique image, so owned items are free re-downloads). The response adds remaining/owned/total_matching and subset_exhausted with a message when you own the whole matching subset."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "benchmark",
                "skin_tone",
                "gender",
                "kind",
                "generator",
                "perturbation",
                "condition",
                "layer",
                "base_id",
                "source_real_id",
                "scene",
                "variant_group",
                "include",
                "limit",
                "offset",
                "cursor",
                "lineage",
                "exclude_owned",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListItemsResponseTypedDict(TypedDict):
    result: ItemListTypedDict


class ListItemsResponse(BaseModel):
    next: Union[
        Callable[[], Optional[ListItemsResponse]],
        Callable[[], Awaitable[Optional[ListItemsResponse]]],
    ]

    result: ItemList
