"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from margen.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from margen.utils import validate_const
import pydantic
from pydantic import model_serializer
from pydantic.functional_validators import AfterValidator
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


UsageTier = Union[
    Literal[
        "test",
        "live",
    ],
    UnrecognizedStr,
]


class UsageTypedDict(TypedDict):
    tier: UsageTier
    balance: int
    r"""Credit balance (images purchasable)."""
    object: Literal["usage"]
    owner: NotRequired[str]


class Usage(BaseModel):
    tier: UsageTier

    balance: int
    r"""Credit balance (images purchasable)."""

    object: Annotated[
        Annotated[Literal["usage"], AfterValidator(validate_const("usage"))],
        pydantic.Field(alias="object"),
    ] = "usage"

    owner: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["owner"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Usage.model_rebuild()
except NameError:
    pass
