"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from margen.errors import MargenError
from margen.models import error as models_error
from margen.types import BaseModel
from typing import List, Optional


class ErrorData(BaseModel):
    error: str
    r"""Human-readable message."""
    code: models_error.Code
    r"""Stable machine-readable error code. Branch on this, not on the message text."""
    param: Optional[str] = None
    r"""The offending query param (invalid_param on an unknown fixed-dimension value)."""
    allowed: Optional[List[str]] = None
    r"""Allowed values for the offending param (invalid_param)."""
    available: Optional[List[models_error.Available]] = None
    r"""Available benchmarks (unknown_benchmark / ambiguous_benchmark)."""
    required: Optional[int] = None
    r"""Credits required (insufficient_credits)."""


@dataclass(unsafe_hash=True)
class Error(MargenError):
    r"""Missing, invalid, or revoked API key."""

    data: ErrorData = field(hash=False)

    def __init__(
        self, data: ErrorData, raw_response: httpx.Response, body: Optional[str] = None
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
